# Default values for wordpress
replicaCount: 1

wordpress:
  image:
    repository: wordpress
    tag: "6.4-apache"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  storage:
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  
  securityContext:
    fsGroup: 33
  
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

mysql:
  image:
    repository: mysql
    tag: "8.0"
    pullPolicy: IfNotPresent
  
  service:
    port: 3306
    targetPort: 3306
  
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  
  storage:
    size: 8Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  
  securityContext:
    fsGroup: 999
  
  livenessProbe:
    exec:
      command:
        - mysqladmin
        - ping
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  
  readinessProbe:
    exec:
      command:
        - mysqladmin
        - ping
    initialDelaySeconds: 5
    periodSeconds: 2
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: wordpress.devopshemantkumar.info
      paths:
        - path: /
          pathType: Prefix
  tls: []

secrets:
  # Use existing secret or create new one
  existingSecret: ""
  mysqlRootPassword: "rootpassword"
  mysqlPassword: "wordpresspass"
  mysqlDatabase: wordpress
  mysqlUser: wordpress

# Pod Disruption Budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod annotations
podAnnotations: {}

# Pod security context
podSecurityContext:
  fsGroup: 2000

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

nameOverride: ""
fullnameOverride: ""