apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}-mysql
  labels:
    {{- include "wordpress.mysql.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: {{ .Values.mysql.service.targetPort }}
      protocol: TCP
      name: mysql
  selector:
    {{- include "wordpress.mysql.selectorLabels" . | nindent 4 }}