{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wordpress.fullname" . }}-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword | default (randAlphaNum 16) | b64enc | quote }}
  mysql-password: {{ .Values.secrets.mysqlPassword | default (randAlphaNum 16) | b64enc | quote }}
  mysql-database: {{ .Values.secrets.mysqlDatabase | b64enc | quote }}
  mysql-user: {{ .Values.secrets.mysqlUser | b64enc | quote }}
{{- end }}